### PR TITLE
fix h3_great_circle_distance accepting degrees instead of rads

### LINKED ISSUE #105: Input for h3_great_circle_distance expects radians, not degrees
The rest of the binding works with degrees, but it appears that `h3_great_circle_distance` expects inputs in radians.

### PR DESCRIPTION
**Pull request by isaacbrodsky**
Fixes #105

### CODE REVIEW

File: src/h3_misc.cpp [hunk 1]
```diff
@@ -247,8 +247,8 @@ static void GreatCircleDistanceFunction(DataChunk &args, ExpressionState &state,
                         .GetValue<double>();
       string_t unit = args.GetValue(4, i).ToString();
 
-      LatLng latLng0 = {.lat = lat0, .lng = lng0};
-      LatLng latLng1 = {.lat = lat1, .lng = lng1};
+      LatLng latLng0 = {.lat = radsToDegs(lat0), .lng = radsToDegs(lng0)};
+      LatLng latLng1 = {.lat = radsToDegs(lat1), .lng = radsToDegs(lng1)};
```
Comment (nrabinowitz) [inline src/h3_misc.cpp:251]: Isn't this backwards? The input is degrees, right?

Comment (isaacbrodsky) [reply src/h3_misc.cpp]: Oops, yes, this is backwards. I've now checked the results against another online calculator & confirmed I get results that look comparable.
