### PR TITLE
Add Parquet test & fix string vector issue

### LINKED ISSUE #17: Getting an error using `h3_h3_to_string` on a H3 cell stored in a column
In my instance of DuckDB this query works fine:

```sql 
select h3_h3_to_string(622236751406759935::ubigint);
```

However when I try to apply `h3_h3_to_string` to a column in my data with H3 cells stored, generated using `h3_latlng_to_cell` I get the following error:

`????INVALID VALUE - Invalid unicode (byte sequence mismatch) detected in value construction????? `

I am using DuckDB 0.7.1 and not the version that is packaged when building the H3 extension

### PR DESCRIPTION
**Pull request by isaacbrodsky**
This may fix #17. I am not entirely sure how the function sort-of worked before, but I am guessing there was a use-after-free on the resulting string vector (or in any case the resulting string vector was invalid.) This changes the function to match the string concat function from duckdb, and adds a test to confirm it works as intended. There is some risk that this doesn't fully fix the issue, my intuition would be if it fails it would be on a larger file.

### CODE REVIEW

File: h3_functions/h3_inspection.cpp [hunk 1]
```diff
@@ -27,9 +27,11 @@ static void StringToH3Function(DataChunk &args, ExpressionState &state, Vector &
 
 static void H3ToStringFunction(DataChunk &args, ExpressionState &state, Vector &result) {
 	auto &inputs = args.data[0];
-	// TODO: Unlikely to be the best option here, look at scalarfunction "format" in printf.cpp
-	UnaryExecutor::Execute<uint64_t, string_t>(inputs, result, args.size(),
-	                                           [&](uint64_t h3) { return StringUtil::Format("%llx", h3); });
+	UnaryExecutor::Execute<uint64_t, string_t>(args.data[0], result, args.size(), [&](uint64_t h3) {
+		auto str = StringUtil::Format("%llx", h3);
+		// TODO: Confirm this does not have any multithreading issues
```
Comment (isaacbrodsky) [inline h3_functions/h3_inspection.cpp:32]: Unclear if this needs further investigation or not.
